length_in_x: 30.0
length_in_y: 30.0
position_x: 0.0
position_y: 0.0
resolution: 0.1
min_variance: 0.000009
max_variance: 0.1 # 0.1
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009 #0.01 #0.0000009
surface_normal_estimation_radius: 0.015
surface_normal_positive_axis: z
time_tolerance: 5.0
